variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
cache:
  paths:
    - .m2/repository

stages: # 定义构建的阶段
  - build
build: # 对应 stages 定义的阶段
  stage: build
  image: image.senses-ai.com/maven:3-jdk-8-mvn-03
  only:
    refs:
      - merge_requests
  tags:  # 即指定运行的runner节点，这里在gitlab管理端可以配置，并且需要给项目开启使用
    - czbk-slave01
  script: # 执行的脚本
    - pwd
    - mvn clean package -Dmaven.test.skip=true
  allow_failure: false   #允许失败
